### ISSUE TITLE
Various Softlocks during matches

### ISSUE THREAD

**Issue by DazeDraco** [Arackulele/GrimoraMod#232] opened 2023-11-23 22:10 UTC
I encountered some bugs during various points throughout the mod and have some clips to showcase what happened

https://clips.twitch.tv/KnottyLitigiousDragonMau5-zqPWPoHGgLlqQNK_

Using the trowel to spawn a Voodoo Doll, it was shot by a sentry, and the game softlocked

https://clips.twitch.tv/AbstemiousSpoopyWolfFUNgineer-hV8ufO2SnXDjbh_i

Haunting sigils were discarded after damage was dealt on my side, then I was softlocked before the opposing sides cards advanced

https://clips.twitch.tv/MuddyPeacefulAsparagusMVGame-yH5nAXSAjTrinLZe

Sentry attempted to kill an Old Mummy, but instead the game softlocked

https://clips.twitch.tv/ResoluteSweetChoughTinyFace-BLhoE6agMu6hCC-I

I won a run, and the achievement popped, but the game forced me back to a glitched version of Act 1. This one is fine and I suspect it's because of using other expansion mods along with Grimora.

The other mods I used were:
The official - Grimora_Mod_Expansion https://inscryption.thunderstore.io/package/Arackulele/Grimora_Mod_Expansion/1.0.0/
RevenantMod https://inscryption.thunderstore.io/package/Orochi_Umbra/RevenantMod/0.0.10/
Fallen_Kingdom https://inscryption.thunderstore.io/package/keks307/Fallen_Kingdom/1.0.1/

**Comment by SarahKirksey** [comment] 2023-11-28 17:32
Note: Twitch deletes videos after a set period of time, and is thus a _really_ bad platform to reference for bug reports.

**Comment by keks307** [comment] 2024-09-07 16:13
First issue is fixed in the newest version. Second issue can not be resolved by us, it cause by BittysSigils Mod. Third issue: can not be resolved b us, it is caused by Revenant Mod. Fourth issue: ???

**Closed by keks307** 2024-09-07 16:13 UTC
